# Generated by Django 6.0 on 2025-12-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google_map_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
