# Generated by Django 6.0 on 2025-12-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_queuesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuesession',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Serving', 'Serving')], default='Waiting', max_length=10),
        ),
    ]
